"""
News export utilities for SustainaBOT
"""
import datetime
import json
from typing import List, Dict

def export_news_to_json(news_data: List[Dict], category: str = "general") -> str:
    """Export news data to JSON format"""
    export_data = {
        "export_timestamp": datetime.datetime.now().isoformat(),
        "category": category,
        "total_articles": len(news_data),
        "articles": news_data
    }
    return json.dumps(export_data, indent=2)

def export_news_to_markdown(news_data: List[Dict], category: str = "general") -> str:
    """Export news data to Markdown format"""
    markdown_content = f"""# Renewable Energy News - {category.title()}

**Export Date:** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Category:** {category.title()}
**Total Articles:** {len(news_data)}

---

"""
    
    for i, article in enumerate(news_data, 1):
        markdown_content += f"""## {i}. {article['title']}

**Summary:** {article['content']}

**Source:** [{article['url']}]({article['url']})

---

"""
    
    markdown_content += f"""
*Generated by SustainaBOT - Environmental Intelligence Assistant*
"""
    
    return markdown_content

def create_news_digest_email(news_data: List[Dict], category: str = "general") -> Dict[str, str]:
    """Create email content for news digest"""
    
    category_emoji = {
        "general": "🌱", "solar": "☀️", "wind": "💨", "hydro": "💧",
        "geothermal": "🌋", "battery": "🔋", "policy": "📋", "investment": "💰"
    }
    
    emoji = category_emoji.get(category, "🌱")
    
    subject = f"{emoji} Renewable Energy News Digest - {category.title()} ({datetime.datetime.now().strftime('%Y-%m-%d')})"
    
    body = f"""
{emoji} **Renewable Energy News Digest**

**Category:** {category.title()}
**Date:** {datetime.datetime.now().strftime("%B %d, %Y")}
**Articles:** {len(news_data)}

---

"""
    
    for i, article in enumerate(news_data, 1):
        body += f"""
**{i}. {article['title']}**

{article['content'][:200]}...

🔗 Read more: {article['url']}

---
"""
    
    body += f"""

📬 *This digest was generated by SustainaBOT*
🌍 *Stay sustainable, stay informed!*
"""
    
    return {
        "subject": subject,
        "body": body
    }